### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Nekromio** [Headline/Lysis-Web#3]
php 7.2, 5.6 not work. When decompiling just a white screen. Did everything according to the instructions on two different hosting.

**Comment by Nekromio** [comment]
If you leave a tick "download", then downloads an empty file. I can even give ftp data, I do not know what to do.

**Comment by kasuganosoras** [comment]
Make sure your website directory has readable and writable access.
It works well on my server. My server php version is 7.3.0RC5.
Try the command: chown -R **<your_webserver_user_name>** **<your_website_directory>**
Such as: `chown -R www:www /data/wwwroot/my-website/`
If it doesn't work, you also can try: chmod -R 755 **<your_website_directory>**

**Comment by Nekromio** [comment]
> Make sure your website directory has readable and writable access.
> It works well on my server. My server php version is 7.3.0RC5.
> Try the command: chown -R **<your_webserver_user_name>** **<your_website_directory>**
> Such as: `chown -R www:www /data/wwwroot/my-website/`
> If it doesn't work, you also can try: chmod -R 755 **<your_website_directory>**

I did all of the above, there is no result. Any other ideas?

**Comment by kasuganosoras** [comment]
Add a new line to the upload.php, behind `<?php`:
```php
error_reporting(E_ALL);
```
Then try to upload a .smx file and see if there is some error or warning content output.

**Comment by kasuganosoras** [comment]
Oh, I remember an important thing. Is Java installed on your server?

If not, you need to install java first, then download and copy the `lysis-java.jar` to your website root directory. (You can find the download link in README.md)

If you don't set the environment variables, please modify upload.php, find `shell_exec`, and change java to absolute path, like `/usr/bin/java`:
```php
$output = shell_exec('/usr/bin/java -jar lysis-java.jar '.$_FILES["fileToUpload"]["tmp_name"]); // get lysis output
```

**Comment by Headline** [comment]
I am going to presume this outstanding issue is fixed. If not please reopen

**Comment by Nekromio** [comment]
Java is installed, but the error is still the same.

java version "1.7.0_261"
OpenJDK Runtime Environment (IcedTea 2.6.22) (7u261-2.6.22-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)

**Comment by Nekromio** [comment]
I wrote error_reporting ( E_ALL);, but nothing has changed. The error log didn't appear anywhere.

**Comment by Nekromio** [comment]
> Я предполагаю, что эта нерешенная проблема исправлена. Если нет, пожалуйста, откройте

Please open it, the problem is not solved.

**Comment by Headline** [comment]
Make sure the php script has +x permissions to execute lysis-java
